import 'package:flutter/material.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';

import '../../../core/models/app_icon.dart';

class CategoryIcon {
  static List<AppIcon> icons = [
    AppIcon(name: 'live_tv_outlined', icon: Icons.live_tv_outlined, label: 'TV', color: Colors.indigo),
    AppIcon(name: 'phone_android_outlined', icon: Icons.phone_android_outlined, label: 'Phone', color: Colors.teal),
    AppIcon(name: 'tshirt-crew', icon: MdiIcons.tshirtCrew, label: 'Clothes', color: Colors.pinkAccent),
    AppIcon(name: 'card_giftcard', icon: Icons.card_giftcard, label: 'Gift', color: Colors.deepPurple),
    AppIcon(name: 'cash', icon: MdiIcons.cash, label: 'Cash', color: Colors.amber),
    AppIcon(name: 'cashMultiple', icon: MdiIcons.cashMultiple, label: 'Cash', color: Colors.green),
    AppIcon(name: 'gift', icon: MdiIcons.gift, label: 'Gift', color: Colors.lightGreen),
    AppIcon(name: 'mic_sharp', icon: Icons.mic_sharp, label: 'Music', color: Colors.deepOrange),
    AppIcon(name: 'check_room', icon: Icons.checkroom, label: 'Clothes', color: Colors.cyan),
    AppIcon(name: 'groups', icon: Icons.groups, label: 'Group', color: Colors.blueAccent),
    AppIcon(name: 'wallet', icon: Icons.wallet, label: 'Wallet', color: Colors.lime),
    AppIcon(name: 'book-open-page-variant-outline', icon: MdiIcons.bookOpenPageVariantOutline, label: 'Book', color: Colors.brown),
    AppIcon(name: 'heart-circle', icon: MdiIcons.heartCircle, label: 'Heart', color: Colors.redAccent),
    AppIcon(name: 'badminton', icon: MdiIcons.badminton, label: 'Sport', color: Colors.greenAccent),
    AppIcon(name: 'baseball', icon: MdiIcons.baseball, label: 'Sport', color: Colors.lightBlue),
    AppIcon(name: 'basketball', icon: MdiIcons.basketball, label: 'Sport', color: Colors.orange),
    AppIcon(name: 'soccer', icon: MdiIcons.soccer, label: 'Sport', color: Colors.yellowAccent),
    AppIcon(name: 'tennisBall', icon: MdiIcons.tennisBall, label: 'Sport', color: Colors.purpleAccent),
    AppIcon(name: 'account-tie', icon: MdiIcons.accountTie, label: 'Business', color: Colors.blueGrey),
    AppIcon(name: 'percent', icon: MdiIcons.percent, label: 'Discount', color: Colors.deepOrangeAccent),
    AppIcon(name: 'parking', icon: MdiIcons.parking, label: 'Parking', color: Colors.grey),
    AppIcon(name: 'emoji-event', icon: Icons.emoji_events, label: 'Event', color: Colors.amberAccent),
    AppIcon(name: 'package-variant', icon: MdiIcons.packageVariant, label: 'Package', color: Colors.brown),
    AppIcon(name: 'notebook', icon: MdiIcons.notebook, label: 'Notebook', color: Colors.indigoAccent),
    AppIcon(name: 'school', icon: MdiIcons.school, label: 'School', color: Colors.blue),
    AppIcon(name: 'phone-classic', icon: MdiIcons.phoneClassic, label: 'Phone', color: Colors.green),
    AppIcon(name: 'movie', icon: MdiIcons.movie, label: 'Movie', color: Colors.red),
    AppIcon(name: 'ring', icon: MdiIcons.ring, label: 'Ring', color: Colors.purple),
    AppIcon(name: 'local_gas_station', icon: Icons.local_gas_station, label: 'Gas', color: Colors.yellow),
    AppIcon(name: 'luggage', icon: Icons.luggage, label: 'Luggage', color: Colors.blueAccent),
    AppIcon(name: 'toolbox', icon: MdiIcons.toolbox, label: 'Toolbox', color: Colors.grey),
    AppIcon(name: 'local_restaurant', icon: Icons.local_restaurant, label: 'Restaurant', color: Colors.redAccent),
    AppIcon(name: 'fastfood', icon: Icons.fastfood, label: 'Fast Food', color: Colors.orangeAccent),
    AppIcon(name: 'food-turkey', icon: MdiIcons.foodTurkey, label: 'Turkey', color: Colors.deepOrange),
    AppIcon(name: 'food-steak', icon: MdiIcons.foodSteak, label: 'Steak', color: Colors.brown),
    AppIcon(name: 'balloon', icon: MdiIcons.balloon, label: 'Balloon', color: Colors.pinkAccent),
    AppIcon(name: 'account_balance', icon: Icons.account_balance, label: 'Bank', color: Colors.indigo),
    AppIcon(name: 'directions_bike', icon: Icons.directions_bike, label: 'Bike', color: Colors.greenAccent),
    AppIcon(name: 'pill', icon: MdiIcons.pill, label: 'Medicine', color: Colors.redAccent),
    AppIcon(name: 'fire', icon: MdiIcons.fire, label: 'Fire', color: Colors.deepOrange),
    AppIcon(name: 'watch', icon: Icons.watch, label: 'Watch', color: Colors.blueGrey),
    AppIcon(name: 'gamepad-variant', icon: MdiIcons.gamepadVariant, label: 'Game', color: Colors.orangeAccent),
    AppIcon(name: 'hamburger', icon: MdiIcons.hamburger, label: 'Burger', color: Colors.red),
    AppIcon(name: 'receipt', icon: Icons.receipt, label: 'Receipt', color: Colors.blue),
    AppIcon(name: 'headset', icon: Icons.headset, label: 'Headset', color: Colors.blueAccent),
    AppIcon(name: 'trending_up', icon: Icons.trending_up, label: 'Investment', color: Colors.green),
    AppIcon(name: 'flower', icon: MdiIcons.flower, label: 'Flower', color: Colors.pink),
    AppIcon(name: 'bus', icon: MdiIcons.bus, label: 'Bus', color: Colors.blue),
    AppIcon(name: 'icecream', icon: Icons.icecream, label: 'Ice Cream', color: Colors.pinkAccent),
    AppIcon(name: 'pedal_bike', icon: Icons.pedal_bike, label: 'Bike', color: Colors.green),
    AppIcon(name: 'hotel', icon: Icons.hotel, label: 'Hotel', color: Colors.indigoAccent),
    AppIcon(name: 'earth', icon: MdiIcons.earth, label: 'Earth', color: Colors.blue),
    AppIcon(name: 'cat', icon: MdiIcons.cat, label: 'Cat', color: Colors.orangeAccent),
    AppIcon(name: 'pets', icon: Icons.pets, label: 'Pets', color: Colors.orange),
    AppIcon(name: 'badge', icon: Icons.badge, label: 'Badge', color: Colors.blue),
    AppIcon(name: 'washing-machine', icon: MdiIcons.washingMachine, label: 'Washing Machine', color: Colors.blueGrey),
    AppIcon(name: 'cake', icon: Icons.cake, label: 'Cake', color: Colors.pink),
    AppIcon(name: 'car', icon: MdiIcons.car, label: 'Car', color: Colors.blueAccent),
    AppIcon(name: 'sofa', icon: MdiIcons.sofa, label: 'Sofa', color: Colors.brown),
    AppIcon(name: 'robot-vacuum', icon: MdiIcons.robotVacuum, label: 'Robot Vacuum', color: Colors.grey),
    AppIcon(name: 'lipstick', icon: MdiIcons.lipstick, label: 'Lipstick', color: Colors.pinkAccent),
    AppIcon(name: 'pencil-ruler', icon: MdiIcons.pencilRuler, label: 'Pencil Ruler', color: Colors.blueGrey),
    AppIcon(name: 'stethoscope', icon: MdiIcons.stethoscope, label: 'Stethoscope', color: Colors.red),
    AppIcon(name: 'bed-empty', icon: MdiIcons.bedEmpty, label: 'Bed', color: Colors.blue),
    AppIcon(name: 'shopping_cart', icon: Icons.shopping_cart, label: 'Shopping Cart', color: Colors.greenAccent),
    AppIcon(name: 'shopping-bag', icon: Icons.shopping_bag, label: 'Shopping Bag', color: Colors.green),
    AppIcon(name: 'hospital-building', icon: MdiIcons.hospitalBuilding, label: 'Hospital', color: Colors.redAccent),
    AppIcon(name: 'google-maps', icon: MdiIcons.googleMaps, label: 'Maps', color: Colors.blue),
    AppIcon(name: 'local_bar_sharp', icon: Icons.local_bar_sharp, label: 'Bar', color: Colors.brown),
    AppIcon(name: 'beer', icon: MdiIcons.beer, label: 'Beer', color: Colors.amber),
    AppIcon(name: 'camera_alt_rounded', icon: Icons.camera_alt_rounded, label: 'Camera', color: Colors.blueAccent),
    AppIcon(name: 'local_cafe', icon: Icons.local_cafe, label: 'Cafe', color: Colors.brown),
    AppIcon(name: 'dog', icon: MdiIcons.dog, label: 'Dog', color: Colors.orange),
    AppIcon(name: 'shoe-sneaker', icon: MdiIcons.shoeSneaker, label: 'Sneaker', color: Colors.blue),
    AppIcon(name: 'shield-account-variant-outline', icon: MdiIcons.shieldAccountVariantOutline, label: 'Security', color: Colors.blueGrey),
    AppIcon(name: 'lightbulb', icon: Icons.lightbulb, label: 'Light', color: Colors.yellowAccent),
    AppIcon(name: 'handshake', icon: MdiIcons.handshake, label: 'Handshake', color: Colors.blue),
    AppIcon(name: 'credit_card', icon: Icons.credit_card, label: 'Credit Card', color: Colors.blueGrey),
    AppIcon(name: 'airport', icon: MdiIcons.airport, label: 'Airport', color: Colors.blue),
    AppIcon(name: 'savings', icon: Icons.savings, label: 'Savings', color: Colors.green),
    AppIcon(name: 'yoga', icon: MdiIcons.yoga, label: 'Yoga', color: Colors.blue),
    AppIcon(name: 'baby-bottle-outline', icon: MdiIcons.babyBottleOutline, label: 'Baby Bottle', color: Colors.pink),
    AppIcon(name: 'tie', icon: MdiIcons.tie, label: 'Tie', color: Colors.blue),
    AppIcon(name: 'truck-delivery-outlined', icon: Icons.local_shipping_outlined, label: 'Delivery', color: Colors.blue),
    AppIcon(name: 'fridge', icon: MdiIcons.fridge, label: 'Fridge', color: Colors.blueGrey),
    AppIcon(name: 'hand-heart', icon: MdiIcons.handHeart, label: 'Heart', color: Colors.redAccent),
    AppIcon(name: 'cell_wifi_outlined', icon: Icons.cell_wifi_outlined, label: 'WiFi', color: Colors.blue),
    AppIcon(name: "water_drop", icon: Icons.water_drop, label: 'Water', color: Colors.blueAccent),
    AppIcon(name: 'broom', icon: MdiIcons.broom, label: 'Broom', color: Colors.brown),
    AppIcon(name: 'cash-minus', icon: MdiIcons.cashMinus, label: 'Cash Minus', color: Colors.redAccent),
    AppIcon(name: 'cash-plus', icon: MdiIcons.cashPlus, label: 'Cash Plus', color: Colors.greenAccent),
    AppIcon(name: 'default', icon: Icons.category, label: 'Default', color: Colors.grey),
  ];


  static AppIcon getIcon(String name) {
    return icons.firstWhere(
      (icon) => icon.name == name,
      orElse: () => AppIcon(
        name: 'default',
        icon: Icons.category,
        label: 'Default',
        color: Colors.grey,
      ),
    );
  }

  static AppIcon defaultIcon() {
    return AppIcon(
      name: 'default',
      icon: Icons.category,
      label: 'Default',
      color: Colors.grey,
    );
  }
}